# Generated by Django 4.0.3 on 2022-04-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=100)),
                ('swedish_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=2000)),
                ('nutrition', models.IntegerField()),
                ('sunlight', models.CharField(max_length=50)),
                ('water', models.CharField(max_length=50)),
                ('replant', models.IntegerField()),
                ('description', models.TextField()),
                ('family', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_subprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('water', models.IntegerField()),
                ('replant', models.IntegerField()),
                ('nutrition', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.plant')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
    ]
