# Generated by Django 4.0.3 on 2022-04-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_plant_user_plant_subprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_subprofile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='nutrition',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='replant',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='water',
            field=models.DateField(),
        ),
    ]
