# Generated by Django 4.0.3 on 2022-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_subprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='nutrition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='sub_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
