# Generated by Django 4.0.3 on 2022-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_plant_subprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_id',
            field=models.CharField(default='001', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='sub_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant_subprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
